// Generated by make_form.py from questions.json. Run createForm() once.
const BASE = "https://basartemiz.github.io/opencode/study/survey"
const QUESTIONS = [
  {
    "id": "background",
    "title": "Which describes you best?",
    "type": "choice",
    "options": [
      "CS / engineering student",
      "Working developer",
      "Other"
    ]
  },
  {
    "id": "q1_suspended",
    "title": "Which file stops a suspended member from borrowing a book?",
    "type": "choice",
    "options": [
      "src/services/members.js",
      "src/services/loans.js",
      "src/http/routes/members.js",
      "src/services/catalog.js",
      "Not sure"
    ],
    "answer": "src/services/loans.js",
    "evidence": "final.diff: the suspended check was added to borrow() in src/services/loans.js; members.js only stores the flag"
  },
  {
    "id": "q2_year",
    "title": "Which file removes books outside the ?from / ?to years from the results?",
    "type": "choice",
    "options": [
      "src/http/routes/books.js",
      "src/services/catalog.js",
      "src/models/book.js",
      "src/db/store.js",
      "Not sure"
    ],
    "answer": "src/services/catalog.js",
    "evidence": "final.diff: routes/books.js only parses from/to; the filter is in search() in src/services/catalog.js"
  },
  {
    "id": "q3_popular",
    "title": "After this session, does GET /reports/popular return the popular books list?",
    "type": "choice",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ],
    "answer": "No",
    "evidence": "The agent's summary and checkpoint 4 claim the route was added, but no route file or server change exists in final.diff; the map marks src/http/routes/reports.js as a missing file"
  },
  {
    "id": "q4_extra",
    "title": "Did the agent change anything that the task did NOT ask for?",
    "type": "choice",
    "options": [
      "Yes",
      "No",
      "Not sure"
    ]
  },
  {
    "id": "q4_what",
    "title": "If yes: what did it change? (one short line)",
    "type": "text",
    "required": false,
    "keywords_from": "hidden_change.json",
    "note": "The hidden change is listed in both views (its own checkpoint on the map, point 5 of the agent's summary), so a ceiling effect is expected here."
  },
  {
    "id": "confidence",
    "title": "How confident are you in your answers?",
    "type": "scale",
    "low": 1,
    "high": 5,
    "low_label": "Guessing",
    "high_label": "Very sure"
  },
  {
    "id": "minutes",
    "title": "Roughly how many minutes did you spend on the page?",
    "type": "number"
  }
]

function createForm() {
  const form = FormApp.create("A short look at a coding agent's work (5 min)")
  form.setDescription(
    "You will open one web page that shows what an AI coding agent did for a task, then answer a few questions. " +
    "There are no wrong people, only unclear pages: if you are unsure, say so. Takes about 5 minutes."
  )
  form.setCollectEmail(false)
  form.setShowLinkToRespondAgain(false)

  const month = form.addMultipleChoiceItem().setTitle("Your birth month").setRequired(true)

  const pageA = form.addPageBreakItem().setTitle("Open this page")
    .setHelpText("Open in a new tab: " + BASE + "/A.html  — look around, then come back here.")
  form.addCheckboxItem().setTitle("I opened the page").setChoiceValues(["Yes"]).setRequired(true)

  const pageB = form.addPageBreakItem().setTitle("Open this page")
    .setHelpText("Open in a new tab: " + BASE + "/B.html  — look around, then come back here.")
  form.addCheckboxItem().setTitle("I opened the page ").setChoiceValues(["Yes"]).setRequired(true)

  const questions = form.addPageBreakItem().setTitle("Questions")
    .setHelpText("Keep the page open while you answer.")
  pageB.setGoToPage(questions) // finishing page A skips page B

  const months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
  month.setChoices(months.map((name, i) => month.createChoice(name, i % 2 === 0 ? pageA : pageB)))

  QUESTIONS.forEach((q) => {
    const required = q.required !== false
    if (q.type === "choice") form.addMultipleChoiceItem().setTitle(q.title).setChoiceValues(q.options).setRequired(required)
    else if (q.type === "text") form.addTextItem().setTitle(q.title).setRequired(required)
    else if (q.type === "scale") form.addScaleItem().setTitle(q.title).setBounds(q.low, q.high).setLabels(q.low_label, q.high_label).setRequired(required)
    else if (q.type === "number") {
      const item = form.addTextItem().setTitle(q.title).setRequired(required)
      item.setValidation(FormApp.createTextValidation().requireNumberBetween(0, 120).build())
    }
  })

  const sheet = SpreadsheetApp.create("Understand survey responses")
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId())
  Logger.log("Share link: " + form.getPublishedUrl())
  Logger.log("Edit link:  " + form.getEditUrl())
  Logger.log("Responses:  " + sheet.getUrl())
}
