#!/usr/bin/env python3
"""Writes create_form.gs (Google Apps Script) from questions.json.

Usage: python3 study/survey/make_form.py <base URL where A.html and B.html are hosted>
Then paste create_form.gs into https://script.google.com and run createForm().
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

if len(sys.argv) != 2:
    sys.exit("usage: make_form.py <base URL, e.g. https://basartemiz.github.io/opencode/study/survey>")
base = sys.argv[1].rstrip("/")
spec = json.loads((HERE / "questions.json").read_text())
for q in spec["questions"]:
    if "TBD" in json.dumps(q):
        sys.exit(f"question {q['id']} still has TBD options; fill them in from the session first")

script = """// Generated by make_form.py from questions.json. Run createForm() once.
const BASE = %(base)s
const QUESTIONS = %(questions)s

function createForm() {
  const form = FormApp.create("A short look at a coding agent's work (5 min)")
  form.setDescription(
    "You will open one web page that shows what an AI coding agent did for a task, then answer a few questions. " +
    "There are no wrong people, only unclear pages: if you are unsure, say so. Takes about 5 minutes."
  )
  form.setCollectEmail(false)
  form.setShowLinkToRespondAgain(false)

  const month = form.addMultipleChoiceItem().setTitle("Your birth month").setRequired(true)

  const pageA = form.addPageBreakItem().setTitle("Open this page")
    .setHelpText("Open in a new tab: " + BASE + "/A.html  — look around, then come back here.")
  form.addCheckboxItem().setTitle("I opened the page").setChoiceValues(["Yes"]).setRequired(true)

  const pageB = form.addPageBreakItem().setTitle("Open this page")
    .setHelpText("Open in a new tab: " + BASE + "/B.html  — look around, then come back here.")
  form.addCheckboxItem().setTitle("I opened the page ").setChoiceValues(["Yes"]).setRequired(true)

  const questions = form.addPageBreakItem().setTitle("Questions")
    .setHelpText("Keep the page open while you answer.")
  pageB.setGoToPage(questions) // finishing page A skips page B

  const months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
  month.setChoices(months.map((name, i) => month.createChoice(name, i %% 2 === 0 ? pageA : pageB)))

  QUESTIONS.forEach((q) => {
    const required = q.required !== false
    if (q.type === "choice") form.addMultipleChoiceItem().setTitle(q.title).setChoiceValues(q.options).setRequired(required)
    else if (q.type === "text") form.addTextItem().setTitle(q.title).setRequired(required)
    else if (q.type === "scale") form.addScaleItem().setTitle(q.title).setBounds(q.low, q.high).setLabels(q.low_label, q.high_label).setRequired(required)
    else if (q.type === "number") {
      const item = form.addTextItem().setTitle(q.title).setRequired(required)
      item.setValidation(FormApp.createTextValidation().requireNumberBetween(0, 120).build())
    }
  })

  const sheet = SpreadsheetApp.create("Understand survey responses")
  form.setDestination(FormApp.DestinationType.SPREADSHEET, sheet.getId())
  Logger.log("Share link: " + form.getPublishedUrl())
  Logger.log("Edit link:  " + form.getEditUrl())
  Logger.log("Responses:  " + sheet.getUrl())
}
""" % {"base": json.dumps(base), "questions": json.dumps(spec["questions"], indent=2, ensure_ascii=False)}

(HERE / "create_form.gs").write_text(script)
print(f"wrote {HERE / 'create_form.gs'}")
