#!/usr/bin/env python3
"""Scores the exported Google Form responses with the answer key.

Usage: python3 study/survey/score.py [responses.csv]   (default: study/data/responses.csv)
Writes study/results/survey_results.csv and study/results/survey_table.md.
Raw counts only; with this many people there is no p-value worth reporting.
"""

import csv
import json
import statistics
import sys
from pathlib import Path

STUDY = Path(__file__).resolve().parent.parent
spec = json.loads((STUDY / "survey/questions.json").read_text())
hidden = json.loads((STUDY / "hidden_change.json").read_text())
by_id = {q["id"]: q for q in spec["questions"]}
source = Path(sys.argv[1]) if len(sys.argv) > 1 else STUDY / "data/responses.csv"
MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"]


def column(row, title):
    for key, value in row.items():
        if key.strip() == title.strip():
            return value.strip()
    return ""


def mentions_hidden(text):
    text = text.lower()
    return any(word in text for word in hidden["keywords"])


scored = [q for q in spec["questions"] if "answer" in q]

rows = []
with open(source, newline="", encoding="utf-8") as handle:
    for raw in csv.DictReader(handle):
        month = column(raw, "Your birth month")
        if month not in MONTHS:
            continue
        row = {"group": "A" if MONTHS.index(month) % 2 == 0 else "B", "background": column(raw, by_id["background"]["title"])}
        for q in scored:
            row[q["id"] + "_correct"] = int(column(raw, q["title"]) == q["answer"])
        extra = column(raw, by_id["q4_extra"]["title"])
        what = column(raw, by_id["q4_what"]["title"])
        row["q4_said_yes"] = int(extra == "Yes")
        row["q4_named_fee"] = int(extra == "Yes" and mentions_hidden(what))
        row["q4_text"] = what
        row["confidence"] = int(column(raw, by_id["confidence"]["title"]) or 0)
        minutes = column(raw, by_id["minutes"]["title"]).replace(",", ".")
        row["minutes"] = float(minutes) if minutes else None
        rows.append(row)

out = STUDY / "results"
out.mkdir(exist_ok=True)
with open(out / "survey_results.csv", "w", newline="", encoding="utf-8") as handle:
    writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()) if rows else ["group"])
    writer.writeheader()
    writer.writerows(rows)

lines = [
    f"Source: {source.name}, {len(rows)} responses. Generated by study/survey/score.py.",
    "",
    "| | A: today's view | B: understand map |",
    "|---|---|---|",
]
groups = {g: [r for r in rows if r["group"] == g] for g in "AB"}


def cell(group, key):
    items = groups[group]
    return f"{sum(r[key] for r in items)} / {len(items)}" if items else "0 / 0"


def median(group, key):
    values = [r[key] for r in groups[group] if r[key] is not None]
    return f"{statistics.median(values):g}" if values else "–"


lines.append(f"| People | {len(groups['A'])} | {len(groups['B'])} |")
for q in scored:
    lines.append(f"| {q['id']}: right answer | {cell('A', q['id'] + '_correct')} | {cell('B', q['id'] + '_correct')} |")
lines += [
    f"| q4: said the agent changed something extra | {cell('A', 'q4_said_yes')} | {cell('B', 'q4_said_yes')} |",
    f"| q4: named the late-fee change | {cell('A', 'q4_named_fee')} | {cell('B', 'q4_named_fee')} |",
    f"| Median confidence (1-5) | {median('A', 'confidence')} | {median('B', 'confidence')} |",
    f"| Median minutes (self-reported) | {median('A', 'minutes')} | {median('B', 'minutes')} |",
]
(out / "survey_table.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
