#!/usr/bin/env python3
"""Counts the answers of the short preference form.

Usage: python3 study/survey/score_preference.py [csv]   (default: study/data/preference.csv)
Writes study/results/preference_table.md. Raw counts only.
"""

import csv
import statistics
import sys
from collections import Counter
from pathlib import Path

STUDY = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1]) if len(sys.argv) > 1 else STUDY / "data/preference.csv"
rows = list(csv.DictReader(open(source, newline="", encoding="utf-8")))


def answers(prefix):
    key = next((k for k in (rows[0] if rows else {}) if k.strip().startswith(prefix)), None)
    return [r[key].strip() for r in rows if key and r[key].strip()]


def count(prefix, order):
    c = Counter(answers(prefix))
    return " · ".join(f"{name}: {c.get(name, 0)}" for name in order)


use = [int(a) for a in answers("Would you use View 2")]
lines = [
    f"Source: {source.name}, {len(rows)} responses. Generated by study/survey/score_preference.py.",
    "",
    f"- Background: {count('Which describes you best', ['CS / engineering student', 'Working developer', 'Other'])}",
    f"- Uses AI coding agents: {count('How often do you use AI coding agents', ['Never', 'Sometimes', 'Every day'])}",
    f"- Would rather check changes with: {count('If an AI agent changed your code', ['View 1', 'View 2', 'No preference'])}",
    f"- Finds where a change happened faster in: {count('In which view would you find faster', ['View 1', 'View 2', 'About the same'])}",
    f"- Would use View 2 (1-5): median {statistics.median(use) if use else '–'}, answers {sorted(use)}",
    "",
    "Why (verbatim):",
    *[f"- {a}" for a in answers("Why?")],
]
out = STUDY / "results"
out.mkdir(exist_ok=True)
(out / "preference_table.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
